let produtosLoja = [
    {
        id: "camisa1",
        nome: "Camisa Casual",
        preco: 45,
        descricao: "Camisa confortável para uso diário.",
        img: "imagens/img-1.jpg",
    },
    {
        id: "camisa2",
        nome: "Camisa Social",
        preco: 100,
        descricao: "Camisa elegante para escritório.",
        img: "imagens/img-2.jpg",
    },
    {
        id: "camiseta1",
        nome: "Camiseta",
        preco: 25,
        descricao: "Camiseta básica para qualquer ocasião.",
        img: "imagens/img-3.jpg",
    },
    {
        id: "terno1",
        nome: "Terno Masculino",
        preco: 300,
        descricao: "Terno completo para eventos formais.",
        img: "imagens/img-4.jpg",
    },
    {
        id: "gravata1",
        nome: "Gravata Masculina",
        preco: 25,
        descricao: "Gravata elegante para ocasiões formais.",
        img: "imagens/img-5.png",
    },
    {
        id: "sapato1",
        nome: "Sapatos Casuais",
        preco: 200,
        descricao: "Sapatos confortáveis para o dia a dia.",
        img: "imagens/img-6.png",
    },
    {
        id: "terno2",
        nome: "Terno Preto",
        preco: 450,
        descricao: "Terno clássico em preto.",
        img: "imagens/img-7.png",
    },
    {
        id: "polo1",
        nome: "Polo",
        preco: 45,
        descricao: "Camisa polo casual.",
        img: "imagens/img-8.png",
    },
    {
        id: "jeans1",
        nome: "Camisa Jeans",
        preco: 85,
        descricao: "Camisa em jeans confortável.",
        img: "imagens/img-9.png",
    },
    {
        id: "calca1",
        nome: "Calça Jeans",
        preco: 120,
        descricao: "Calça jeans básica.",
        img: "imagens/img-10.png",
    },
    {
        id: "bone1",
        nome: "Boné Básico",
        preco: 35,
        descricao: "Boné casual.",
        img: "imagens/img-11.png",
    },
    {
        id: "bota1",
        nome: "Botas de Couro",
        preco: 350,
        descricao: "Botas resistentes e elegantes.",
        img: "imagens/img-12.png",
    },
];
